export const foodItems = [
  // --- McDonald's (mcd) ---
  {
    name: "Big Mac",
    review: "The classic burger with two beef patties and special sauce.",
    rating: 9.5,
    image: "images/mcd/bigmac.avif",
    restaurant: "mcd",
    menu: "lunch",
  },
  {
    name: "Quarter Pounder with Cheese",
    review: "A fresh beef patty cooked to order with melted cheese.",
    rating: 8.8,
    image: "images/mcd/qpc.avif",
    restaurant: "mcd",
    menu: "lunch",
  },
  {
    name: "Spicy McCrispy",
    review: "Southern style fried chicken sandwich with a spicy kick.",
    rating: 4.5,
    image: "images/mcd/spicychicken.avif",
    restaurant: "mcd",
    menu: "lunch",
  },
  {
    name: "Filet-O-Fish",
    review: "Wild-caught fish with melty American cheese and tartar sauce.",
    rating: 7.2,
    image: "images/mcd/filet.avif",
    restaurant: "mcd",
    menu: "lunch",
  },
  {
    name: "World Famous Fries",
    review: "Crispy, golden, and perfectly salted.",
    rating: 10,
    image: "images/mcd/mcdfries.avif",
    restaurant: "mcd",
    menu: "lunch",
  },
  {
    name: "Bacon, Egg & Cheese Bagel",
    review:
      "Toasted bagel with butter, thick-cut applewood smoked bacon, and egg.",
    rating: 9,
    image: "images/mcd/bagel.avif",
    restaurant: "mcd",
    menu: "breakfast",
  },
  {
    name: "Sausage, Egg & Cheese McGriddle",
    review: "Soft, warm griddle cakes with the sweet taste of maple.",
    rating: 9.2,
    image: "images/mcd/mcgriddle.avif",
    restaurant: "mcd",
    menu: "breakfast",
  },
  {
    name: "Hash Brown",
    review: "Crispy and golden brown on the outside, fluffy on the inside.",
    rating: 8.5,
    image: "images/mcd/hashbrown.avif",
    restaurant: "mcd",
    menu: "breakfast",
  },
  {
    name: "Coca-Cola",
    review: "Ice-cold Coca-Cola fountain drink.",
    rating: 8,
    image: "images/mcd/coke.avif",
    restaurant: "mcd",
    menu: "lunch",
  },
  {
    name: "Vanilla Cone",
    review: "Creamy vanilla soft serve in a crispy cone.",
    rating: 8.7,
    image: "images/mcd/mcdIceCream.avif",
    restaurant: "mcd",
    menu: "lunch",
  },

  // --- Burger King (bk) ---
  {
    name: "Whopper",
    review:
      "A ¼ lb* flame-grilled beef patty topped with juicy tomatoes and fresh lettuce.",
    rating: 9,
    image: "images/bk/whopper.avif",
    restaurant: "bk",
    menu: "lunch",
  },
  {
    name: "Bacon Double Cheeseburger",
    review: "Two flame-grilled patties with bacon and melted American cheese.",
    rating: 8.9,
    image: "images/bk/doublebacon.avif",
    restaurant: "bk",
    menu: "lunch",
  },
  {
    name: "Chicken Sandwich",
    review: "Crispy white meat chicken breast with savory sauce.",
    rating: 8.3,
    image: "images/bk/chickensandwich.avif",
    restaurant: "bk",
    menu: "lunch",
  },
  {
    name: "Chicken Jr.",
    review:
      "A classic crispy chicken patty topped with chopped lettuce and mayo.",
    rating: 7.5,
    image: "images/bk/chickenjr.webp",
    restaurant: "bk",
    menu: "lunch",
  },
  {
    name: "Chicken Fries",
    review: "Breaded, crispy white meat chicken perfect for dipping.",
    rating: 8.8,
    image: "images/bk/chickenfries.avif",
    restaurant: "bk",
    menu: "lunch",
  },
  {
    name: "Chicken Nuggets",
    review: "Bite-sized, golden brown and crispy.",
    rating: 7,
    image: "images/bk/nuggets.avif",
    restaurant: "bk",
    menu: "lunch",
  },
  {
    name: "Classic Fries",
    review: "Piping hot, thick cut salted french fries.",
    rating: 8.2,
    image: "images/bk/fries.avif",
    restaurant: "bk",
    menu: "lunch",
  },
  {
    name: "Onion Rings",
    review: "Golden brown and breaded onion rings.",
    rating: 8.5,
    image: "images/bk/onion.avif",
    restaurant: "bk",
    menu: "lunch",
  },
  {
    name: "Croissan'wich",
    review: "Flaky croissant with savory sausage, egg, and cheese.",
    rating: 8.6,
    image: "images/bk/croissant.webp",
    restaurant: "bk",
    menu: "breakfast",
  },
  {
    name: "Hash Browns",
    review: "Golden brown potato coins.",
    rating: 7.8,
    image: "images/bk/hashbrowns.webp",
    restaurant: "bk",
    menu: "breakfast",
  },
  {
    name: "Frozen Fanta Blue Raspberry",
    review: "A sweet and icy blue raspberry treat.",
    rating: 9,
    image: "images/bk/frozendrink.avif",
    restaurant: "bk",
    menu: "breakfast",
  },
];
